# BEGIN
spring:
  profiles:
    active: development

---
spring:
  profiles: development
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password: 123
---
spring:
  profiles: stage
  datasource:
    url: jdbc:h2:file:./test
    username: admin
    password: admin
# END
